export const LANG = {
  SUCCESS: "Success!",
  ERROR: "Error!",
  APIERROR: "Oops! Something went wrong there, Please try again.",
  FIELD_TYPES: {
    text: "Text",
    date: "Date",
    email: "Email",
    numeric: "Numeric",
    textarea: "Textarea",
    dropdown: "Dropdown",
    multiselect: "Multiselect",
    checkbox: "Checkbox",
    radio: "Radio",
    boolean: "Boolean",
    // rating: "Rating",
    file: "File",
  },
  FORM_STATUS: {
    DRAFT: "DRAFT",
    NEW: "NEW",
  },
  COL: {
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    5: 5,
    6: 6,
    7: 7,
    8: 8,
    9: 9,
    10: 10,
    11: 11,
    12: 12,
  },
  DEFAULT_COL: 12,
  FIELD: "field",
  SEPARATOR: "separator",
  HEADING: "heading",
  NUMBER: "number",
  CANCEL: "Cancel",
  REMOVE: "Remove",
  CONFIRM_TO_REMOVE: "Confirm to remove",
};
