export const LANG = {
  FIELD_TYPES: {
    boolean: "Boolean",
    checkbox: "Checkbox",
    date: "Date",
    dropdown: "Dropdown",
    email: "Email",
    numeric: "Numeric",
    radio: "Radio",
    rating: "Rating",
    text: "Text",
    textarea: "Textarea",
  },
  COL: {
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    5: 5,
    6: 6,
    7: 7,
    8: 8,
    9: 9,
    10: 10,
    11: 11,
    12: 12,
  },
  DEFAULT_COL: 4,
  FIELD: "field",
  SEPARATOR: "separator",
  HEADING: "heading",
  NUMBER: "number",
  CANCEL: "Cancel",
  REMOVE: "Remove",
  CONFIRM_TO_REMOVE: "Confirm to remove",
};
